# Generated by Django 2.2.7 on 2019-12-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App001', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('nation', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=1)),
                ('idnum', models.CharField(max_length=18)),
                ('address', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
